#!/usr/bin/perl -w

sub register {
    my ( $self, $qp ) = @_;

    $self->register_hook( "auth-plain", "authcpw" );
    $self->register_hook( "auth-login", "authcpw");

}

sub authcpw {
    my ( $self, $transaction, $method, $user, $passClear, $passHash, $ticket ) =
      @_;

    my $binary = $self->qp->config("smtpauth-checkpassword")
      or return (DECLINED);
    return(DECLINED) if ( ! -x $binary );

    my ($untainted) = $binary =~ /^(.*)$/;

    open(CPW,"|$untainted /usr/bin/true 3<&0");
    printf(CPW "%s\0%s\0Y123456\0",$user,$passClear);
    close(CPW);

    my $status = $?;

    return(DECLINED) if ( $status != 0 );
   $self->connection->notes('authuser',$user); 
	$self->qp->connection->notes('whitelist', 1);
$self->connection->relay_client(1);    
return ( OK, "authcheckpassword" );
}

